name: Native Checks

on:
  workflow_dispatch:
  pull_request:
    branches: ['develop']
    paths:
      - .github/**
      - .cargo/**
      - ./src-tauri/**
  push:
    branches: ['develop']
    paths:
      - .github/**
      - .cargo/**
      - ./src-tauri/**


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Install webkit2gtk (ubuntu only)
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0
      - name: Run linter
        working-directory: ./src-tauri
        run: cargo clippy