name: Web Checks

on:
  workflow_dispatch:
  pull_request:
    branches: ['develop']
    paths:
      - .github/**
      - .eslintrc.json
      - ./src/**
  push:
    branches: ['develop']
    paths:
      - .github/**
      - .eslintrc.json
      - ./src/**

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Run linter
        run: npx oxlint@latest -c ./.eslintrc.json ./src